# Generated by Django 4.0 on 2021-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_pedido_cliente_pedido_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='tags',
            field=models.ManyToManyField(to='contas.Tag'),
        ),
    ]
