# Generated by Django 4.0 on 2021-12-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_tag_pedido_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tags',
        ),
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(to='contas.Tag'),
        ),
    ]
