# Generated by Django 4.0 on 2021-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_remove_pedido_tags_produto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
