# Generated by Django 4.0 on 2021-12-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
